name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'  # متوافق مع net9.0 في مشروعك

    - name: Restore dependencies
      run: dotnet restore TodoSolution.sln

    - name: Build solution
      run: dotnet build TodoSolution.sln --configuration Release --no-restore

    - name: Run tests (اختياري إذا عندك مشروع اختبارات)
      run: dotnet test TodoSolution.sln --no-build --verbosity normal
